// Code generated by github.com/joshdk/licensor/spdxgen. DO NOT EDIT.

package spdx

func init() {
	licenses = append(licenses, License{
		Deprecated:       false,
		Identifier:       "Dotseqn",
		Name:             "Dotseqn License",
		OSIApproved:      false,
		StandardHeader:   "",
		StandardTemplate: "Copyright (C) 1995 by Donald Arseneau\nThis file may be freely transmitted and reproduced, but it may not be changed unless the name is changed also (except that you may freely change the paper-size option for \\documentclass).\nThis notice must be left intact.",
		Text:             "Copyright (C) 1995 by Donald Arseneau\nThis file may be freely transmitted and reproduced, but it may not be changed unless the name is changed also (except that you may freely change the paper-size option for \\documentclass).\nThis notice must be left intact.",
		URIs:             []string{"https://fedoraproject.org/wiki/Licensing/Dotseqn"},
	})
}
