// Code generated by github.com/joshdk/licensor/spdxgen. DO NOT EDIT.

package spdx

func init() {
	licenses = append(licenses, License{
		Deprecated:       false,
		Identifier:       "Crossword",
		Name:             "Crossword License",
		OSIApproved:      false,
		StandardHeader:   "",
		StandardTemplate: "<<beginOptional>> Copyright (C) 1995-2009 Gerd Neugebauer<<endOptional>>\ncwpuzzle.dtx is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY. No author or distributor accepts responsibility to anyone for the consequences of using it or for whether it serves any particular purpose or works at all, unless he says so in writing.\n.\nEveryone is granted permission to copy, modify and redistribute cwpuzzle.dtx, provided this copyright notice is preserved and any modifications are indicated.",
		Text:             "Copyright (C) 1995-2009 Gerd Neugebauer\ncwpuzzle.dtx is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY. No author or distributor accepts responsibility to anyone for the consequences of using it or for whether it serves any particular purpose or works at all, unless he says so in writing.\n.\nEveryone is granted permission to copy, modify and redistribute cwpuzzle.dtx, provided this copyright notice is preserved and any modifications are indicated.",
		URIs:             []string{"https://fedoraproject.org/wiki/Licensing/Crossword"},
	})
}
