// Code generated by github.com/joshdk/licensor/spdxgen. DO NOT EDIT.

package spdx

func init() {
	licenses = append(licenses, License{
		Deprecated:       false,
		Identifier:       "Newsletr",
		Name:             "Newsletr License",
		OSIApproved:      false,
		StandardHeader:   "",
		StandardTemplate: "Copyright 1989--2004 by Hunter Goatley.\nPermission is granted to anyone to use this software for any purpose on any computer system, and to redistribute it freely, subject to the following restrictions:\n   <<var;name=\"bullet\";original=\"1.\";match=\".{0,20}\">> This software is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.\n   <<var;name=\"bullet\";original=\"2.\";match=\".{0,20}\">> Altered versions must be plainly marked as such, and must not be misrepresented as being the original software.",
		Text:             "Copyright 1989--2004 by Hunter Goatley.\nPermission is granted to anyone to use this software for any purpose on any computer system, and to redistribute it freely, subject to the following restrictions:\n   1. This software is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.\n   2. Altered versions must be plainly marked as such, and must not be misrepresented as being the original software.",
		URIs:             []string{"https://fedoraproject.org/wiki/Licensing/Newsletr"},
	})
}
