// Code generated by github.com/joshdk/license/spdxgen. DO NOT EDIT.

package spdx

func init() {
	licenses = append(licenses, License{
		Deprecated:       false,
		Identifier:       "Newsletr",
		Name:             "Newsletr License",
		OSIApproved:      false,
		StandardHeader:   "",
		StandardTemplate: "Copyright 1989--2004 by Hunter Goatley.   \n\nPermission is granted to anyone to use this software for any purpose  on any computer system, and to redistribute it freely, subject to the  following restrictions:   \n\n1. This software is distributed in the hope that it will be useful,  but WITHOUT ANY WARRANTY; without even the implied warranty of  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.   \n\n2. Altered versions must be plainly marked as such, and must not be  misrepresented as being the original software.",
		Text:             "Copyright 1989--2004 by Hunter Goatley.   \n\nPermission is granted to anyone to use this software for any purpose  on any computer system, and to redistribute it freely, subject to the  following restrictions:   \n\n1. This software is distributed in the hope that it will be useful,  but WITHOUT ANY WARRANTY; without even the implied warranty of  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.   \n\n2. Altered versions must be plainly marked as such, and must not be  misrepresented as being the original software.",
		URIs:             []string{"https://fedoraproject.org/wiki/Licensing/Newsletr"},
	})
}
