// Code generated by github.com/joshdk/licensor/spdxgen. DO NOT EDIT.

package spdx

func init() {
	licenses = append(licenses, License{
		Deprecated:       false,
		Identifier:       "diffmark",
		Name:             "diffmark license",
		OSIApproved:      false,
		StandardHeader:   "",
		StandardTemplate: "1. you can do what you want with it\n2. I refuse any responsibility for the consequences",
		Text:             "1. you can do what you want with it\n2. I refuse any responsibility for the consequences",
		URIs:             []string{"https://fedoraproject.org/wiki/Licensing/diffmark"},
	})
}
