// Code generated by github.com/joshdk/license/spdxgen. DO NOT EDIT.

package spdx

func init() {
	licenses = append(licenses, License{
		Deprecated:       false,
		Identifier:       "NTP",
		Name:             "NTP License",
		OSIApproved:      true,
		StandardHeader:   "",
		StandardTemplate: "NTP License (NTP)\n\nCopyright (c) <<var;name=copyright;original=(CopyrightHoldersName) (From 4-digit-year)-(To 4-digit-year);match=.+>>\n\nPermission to use, copy, modify, and distribute this software and its documentation for any purpose with or without fee is hereby granted, provided that the above copyright notice appears in all copies and that both the copyright notice and this permission notice appear in supporting documentation, and that the name <<var;name=TMname;original=(TrademarkedName);match=.+>> not be used in advertising or publicity pertaining to distribution of the software without specific, written prior permission. <<var;name=TMname;original=(TrademarkedName);match=.+>> makes no representations about the suitability this software for any purpose. It is provided \"as is\" without express or implied warranty.",
		Text:             "NTP License (NTP)\n\nCopyright (c) (CopyrightHoldersName) (From 4-digit-year)-(To 4-digit-year)\n\nPermission to use, copy, modify, and distribute this software and its documentation for any purpose with or without fee is hereby granted, provided that the above copyright notice appears in all copies and that both the copyright notice and this permission notice appear in supporting documentation, and that the name (TrademarkedName) not be used in advertising or publicity pertaining to distribution of the software without specific, written prior permission. (TrademarkedName) makes no representations about the suitability this software for any purpose. It is provided \"as is\" without express or implied warranty.",
		URIs:             []string{"http://www.opensource.org/licenses/NTP"},
	})
}
