// Code generated by github.com/joshdk/licensor/spdxgen. DO NOT EDIT.

package spdx

func init() {
	licenses = append(licenses, License{
		Deprecated:       false,
		Identifier:       "Spencer-94",
		Name:             "Spencer License 94",
		OSIApproved:      false,
		StandardHeader:   "",
		StandardTemplate: "<<beginOptional>> Copyright 1992, 1993, 1994 Henry Spencer. All rights reserved.<<endOptional>>\nThis software is not subject to any license of the American Telephone and Telegraph Company or of the Regents of the University of California.\nPermission is granted to anyone to use this software for any purpose on any computer system, and to alter it and redistribute it, subject to the following restrictions:\n   <<var;name=\"bullet\";original=\"1.\";match=\".{0,20}\">> The author is not responsible for the consequences of use of this software, no matter how awful, even if they arise from flaws in it.\n   <<var;name=\"bullet\";original=\"2.\";match=\".{0,20}\">> The origin of this software must not be misrepresented, either by explicit claim or by omission. Since few users ever read sources, credits must appear in the documentation.\n   <<var;name=\"bullet\";original=\"3.\";match=\".{0,20}\">> Altered versions must be plainly marked as such, and must not be misrepresented as being the original software. Since few users ever read sources, credits must appear in the documentation.\n   <<var;name=\"bullet\";original=\"4.\";match=\".{0,20}\">> This notice may not be removed or altered.",
		Text:             "Copyright 1992, 1993, 1994 Henry Spencer. All rights reserved.\nThis software is not subject to any license of the American Telephone and Telegraph Company or of the Regents of the University of California.\nPermission is granted to anyone to use this software for any purpose on any computer system, and to alter it and redistribute it, subject to the following restrictions:\n   1. The author is not responsible for the consequences of use of this software, no matter how awful, even if they arise from flaws in it.\n   2. The origin of this software must not be misrepresented, either by explicit claim or by omission. Since few users ever read sources, credits must appear in the documentation.\n   3. Altered versions must be plainly marked as such, and must not be misrepresented as being the original software. Since few users ever read sources, credits must appear in the documentation.\n   4. This notice may not be removed or altered.",
		URIs:             []string{"https://fedoraproject.org/wiki/Licensing/Henry_Spencer_Reg-Ex_Library_License"},
	})
}
