// Code generated by github.com/joshdk/licensor/spdxgen. DO NOT EDIT.

package spdx

func init() {
	licenses = append(licenses, License{
		Deprecated:       false,
		Identifier:       "diffmark",
		Name:             "diffmark license",
		OSIApproved:      false,
		StandardHeader:   "",
		StandardTemplate: "\n   <<var;name=\"bullet\";original=\"1.\";match=\".{0,20}\">> you can do what you want with it\n   <<var;name=\"bullet\";original=\"2.\";match=\".{0,20}\">> I refuse any responsibility for the consequences",
		Text:             "\n   1. you can do what you want with it\n   2. I refuse any responsibility for the consequences",
		URIs:             []string{"https://fedoraproject.org/wiki/Licensing/diffmark"},
	})
}
