// Code generated by github.com/joshdk/license/spdxgen. DO NOT EDIT.

package spdx

func init() {
	licenses = append(licenses, License{
		Deprecated:       false,
		Identifier:       "EFL-2.0",
		Name:             "Eiffel Forum License v2.0",
		OSIApproved:      true,
		StandardHeader:   "",
		StandardTemplate: "Eiffel Forum License, version 2\n\n1. Permission is hereby granted to use, copy, modify and/or distribute this package, provided that: \n     - copyright notices are retained unchanged, \n     - any distribution of this package, whether modified or not, includes this license text.\n\n2. Permission is hereby also granted to distribute binary programs which depend on this package. If the binary program depends on a modified version of this package, you are encouraged to publicly release the modified version of this package. \n\nTHIS PACKAGE IS PROVIDED \"AS IS\" AND WITHOUT WARRANTY. ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHORS BE LIABLE TO ANY PARTY FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES ARISING IN ANY WAY OUT OF THE USE OF THIS PACKAGE. ",
		Text:             "Eiffel Forum License, version 2\n\n1. Permission is hereby granted to use, copy, modify and/or distribute this package, provided that: \n     - copyright notices are retained unchanged, \n     - any distribution of this package, whether modified or not, includes this license text.\n\n2. Permission is hereby also granted to distribute binary programs which depend on this package. If the binary program depends on a modified version of this package, you are encouraged to publicly release the modified version of this package. \n\nTHIS PACKAGE IS PROVIDED \"AS IS\" AND WITHOUT WARRANTY. ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHORS BE LIABLE TO ANY PARTY FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES ARISING IN ANY WAY OUT OF THE USE OF THIS PACKAGE. ",
		URIs:             []string{"http://www.eiffel-nice.org/license/eiffel-forum-license-2.html", "http://opensource.org/licenses/EFL-2.0"},
	})
}
