// Code generated by github.com/joshdk/license/spdxgen. DO NOT EDIT.

package spdx

func init() {
	licenses = append(licenses, License{
		Deprecated:       false,
		Identifier:       "dvipdfm",
		Name:             "dvipdfm License",
		OSIApproved:      false,
		StandardHeader:   "",
		StandardTemplate: "A modified version of this file may be distributed, but it should be distributed with a *different* name. Changed files must be distributed *together with a complete and unchanged* distribution of these files.",
		Text:             "A modified version of this file may be distributed, but it should be distributed with a *different* name. Changed files must be distributed *together with a complete and unchanged* distribution of these files.",
		URIs:             []string{"https://fedoraproject.org/wiki/Licensing/dvipdfm"},
	})
}
