// Code generated by github.com/joshdk/licensor/spdxgen. DO NOT EDIT.

package spdx

func init() {
	licenses = append(licenses, License{
		Deprecated:       false,
		Identifier:       "EFL-1.0",
		Name:             "Eiffel Forum License v1.0",
		OSIApproved:      true,
		StandardHeader:   "",
		StandardTemplate: "<<beginOptional>> Eiffel Forum License, version 1<<endOptional>>\nPermission is hereby granted to use, copy, modify and/or distribute this package, provided that:\n   <<var;name=\"bullet\";original=\"-\";match=\".{0,20}\">> copyright notices are retained unchanged\n   <<var;name=\"bullet\";original=\"-\";match=\".{0,20}\">> any distribution of this package, whether modified or not, includes this file\nPermission is hereby also granted to distribute binary programs which depend on this package, provided that:\n   <<var;name=\"bullet\";original=\"-\";match=\".{0,20}\">> if the binary program depends on a modified version of this package, you must publicly release the modified version of this package\nTHIS PACKAGE IS PROVIDED \"AS IS\" AND WITHOUT WARRANTY. ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHORS BE LIABLE TO ANY PARTY FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES ARISING IN ANY WAY OUT OF THE USE OF THIS PACKAGE.",
		Text:             "Eiffel Forum License, version 1\nPermission is hereby granted to use, copy, modify and/or distribute this package, provided that:\n   - copyright notices are retained unchanged\n   - any distribution of this package, whether modified or not, includes this file\nPermission is hereby also granted to distribute binary programs which depend on this package, provided that:\n   - if the binary program depends on a modified version of this package, you must publicly release the modified version of this package\nTHIS PACKAGE IS PROVIDED \"AS IS\" AND WITHOUT WARRANTY. ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHORS BE LIABLE TO ANY PARTY FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES ARISING IN ANY WAY OUT OF THE USE OF THIS PACKAGE.",
		URIs:             []string{"http://www.eiffel-nice.org/license/forum.txt", "http://opensource.org/licenses/EFL-1.0"},
	})
}
