// Code generated by github.com/joshdk/licensor/spdxgen. DO NOT EDIT.

package spdx

func init() {
	licenses = append(licenses, License{
		Deprecated:       false,
		Identifier:       "GL2PS",
		Name:             "GL2PS License",
		OSIApproved:      false,
		StandardHeader:   "",
		StandardTemplate: "<<beginOptional>> GL2PS LICENSE Version 2, November 2003<<endOptional>>\nCopyright (C) 2003, Christophe Geuzaine\nPermission to use, copy, and distribute this software and its documentation for any purpose with or without fee is hereby granted, provided that the copyright notice appear in all copies and that both that copyright notice and this permission notice appear in supporting documentation.\nPermission to modify and distribute modified versions of this software is granted, provided that:\n   <<var;name=\"bullet\";original=\"1)\";match=\".{0,20}\">> the modifications are licensed under the same terms as this software;\n   <<var;name=\"bullet\";original=\"2)\";match=\".{0,20}\">> you make available the source code of any modifications that you distribute, either on the same media as you distribute any executable or other form of this software, or via a mechanism generally accepted in the software development community for the electronic transfer of data.\nThis software is provided \"as is\" without express or implied warranty.",
		Text:             "GL2PS LICENSE Version 2, November 2003\nCopyright (C) 2003, Christophe Geuzaine\nPermission to use, copy, and distribute this software and its documentation for any purpose with or without fee is hereby granted, provided that the copyright notice appear in all copies and that both that copyright notice and this permission notice appear in supporting documentation.\nPermission to modify and distribute modified versions of this software is granted, provided that:\n   1) the modifications are licensed under the same terms as this software;\n   2) you make available the source code of any modifications that you distribute, either on the same media as you distribute any executable or other form of this software, or via a mechanism generally accepted in the software development community for the electronic transfer of data.\nThis software is provided \"as is\" without express or implied warranty.",
		URIs:             []string{"http://www.geuz.org/gl2ps/COPYING.GL2PS"},
	})
}
