// Code generated by github.com/joshdk/licensor/spdxgen. DO NOT EDIT.

package spdx

func init() {
	licenses = append(licenses, License{
		Deprecated:       false,
		Identifier:       "Spencer-86",
		Name:             "Spencer License 86",
		OSIApproved:      false,
		StandardHeader:   "",
		StandardTemplate: "Copyright (c) 1986 by University of Toronto. Written by Henry Spencer. Not derived from licensed software. \n\nPermission is granted to anyone to use this software for any purpose on any computer system, and to redistribute it freely, subject to the following restrictions: \n\n1. The author is not responsible for the consequences of use of this software, no matter how awful, even if they arise from defects in it. \n\n2. The origin of this software must not be misrepresented, either by explicit claim or by omission. \n\n3. Altered versions must be plainly marked as such, and must not be misrepresented as being the original software. \n\nBeware that some of this code is subtly aware of the way operator precedence is structured in regular expressions. Serious changes in regular-expression syntax might require a total rethink.",
		Text:             "Copyright (c) 1986 by University of Toronto. Written by Henry Spencer. Not derived from licensed software. \n\nPermission is granted to anyone to use this software for any purpose on any computer system, and to redistribute it freely, subject to the following restrictions: \n\n1. The author is not responsible for the consequences of use of this software, no matter how awful, even if they arise from defects in it. \n\n2. The origin of this software must not be misrepresented, either by explicit claim or by omission. \n\n3. Altered versions must be plainly marked as such, and must not be misrepresented as being the original software. \n\nBeware that some of this code is subtly aware of the way operator precedence is structured in regular expressions. Serious changes in regular-expression syntax might require a total rethink.",
		URIs:             []string{"https://fedoraproject.org/wiki/Licensing/Henry_Spencer_Reg-Ex_Library_License"},
	})
}
