// Code generated by github.com/joshdk/licensor/spdxgen. DO NOT EDIT.

package spdx

func init() {
	licenses = append(licenses, License{
		Deprecated:       false,
		Identifier:       "Zlib",
		Name:             "zlib License",
		OSIApproved:      true,
		StandardHeader:   "",
		StandardTemplate: "<<beginOptional>> zlib License<<endOptional>><<beginOptional>> Copyright (c) <year> <copyright holders><<endOptional>>\nThis software is provided 'as-is', without any express or implied warranty. In no event will the authors be held liable for any damages arising from the use of this software.\nPermission is granted to anyone to use this software for any purpose, including commercial applications, and to alter it and redistribute it freely, subject to the following restrictions:\n   <<var;name=\"bullet\";original=\"1.\";match=\".{0,20}\">> The origin of this software must not be misrepresented; you must not claim that you wrote the original software. If you use this software in a product, an acknowledgment in the product documentation would be appreciated but is not required.\n   <<var;name=\"bullet\";original=\"2.\";match=\".{0,20}\">> Altered source versions must be plainly marked as such, and must not be misrepresented as being the original software.\n   <<var;name=\"bullet\";original=\"3.\";match=\".{0,20}\">> This notice may not be removed or altered from any source distribution.",
		Text:             "zlib License Copyright (c) <year> <copyright holders>\nThis software is provided 'as-is', without any express or implied warranty. In no event will the authors be held liable for any damages arising from the use of this software.\nPermission is granted to anyone to use this software for any purpose, including commercial applications, and to alter it and redistribute it freely, subject to the following restrictions:\n   1. The origin of this software must not be misrepresented; you must not claim that you wrote the original software. If you use this software in a product, an acknowledgment in the product documentation would be appreciated but is not required.\n   2. Altered source versions must be plainly marked as such, and must not be misrepresented as being the original software.\n   3. This notice may not be removed or altered from any source distribution.",
		URIs:             []string{"http://www.zlib.net/zlib_license.html", "http://www.opensource.org/licenses/Zlib"},
	})
}
