// Code generated by github.com/joshdk/licensor/spdxgen. DO NOT EDIT.

package spdx

func init() {
	licenses = append(licenses, License{
		Deprecated:       false,
		Identifier:       "Cube",
		Name:             "Cube License",
		OSIApproved:      false,
		StandardHeader:   "",
		StandardTemplate: "Cube game engine source code, 20 dec 2003 release.\n\nCopyright (C) 2001-2003 Wouter van Oortmerssen.\n\nThis software is provided 'as-is', without any express or implied warranty. In no event will the authors be held liable for any damages arising from the use of this software.\n\nPermission is granted to anyone to use this software for any purpose, including commercial applications, and to alter it and redistribute it freely, subject to the following restrictions:\n\n     1. The origin of this software must not be misrepresented; you must not claim that you wrote the original software. If you use this software in a product, an acknowledgment in the product documentation would be appreciated but is not required. \n\n     2. Altered source versions must be plainly marked as such, and must not be misrepresented as being the original software. \n\n     3. This notice may not be removed or altered from any source distribution.\n\nadditional clause specific to Cube:\n\n     4. Source versions may not be \"relicensed\" under a different license without my explicitly written permission.",
		Text:             "Cube game engine source code, 20 dec 2003 release.\n\nCopyright (C) 2001-2003 Wouter van Oortmerssen.\n\nThis software is provided 'as-is', without any express or implied warranty. In no event will the authors be held liable for any damages arising from the use of this software.\n\nPermission is granted to anyone to use this software for any purpose, including commercial applications, and to alter it and redistribute it freely, subject to the following restrictions:\n\n     1. The origin of this software must not be misrepresented; you must not claim that you wrote the original software. If you use this software in a product, an acknowledgment in the product documentation would be appreciated but is not required. \n\n     2. Altered source versions must be plainly marked as such, and must not be misrepresented as being the original software. \n\n     3. This notice may not be removed or altered from any source distribution.\n\nadditional clause specific to Cube:\n\n     4. Source versions may not be \"relicensed\" under a different license without my explicitly written permission.",
		URIs:             []string{"https://fedoraproject.org/wiki/Licensing/Cube"},
	})
}
