// Code generated by github.com/joshdk/licensor/spdxgen. DO NOT EDIT.

package spdx

func init() {
	licenses = append(licenses, License{
		Deprecated:       false,
		Identifier:       "HaskellReport",
		Name:             "Haskell Language Report License",
		OSIApproved:      false,
		StandardHeader:   "",
		StandardTemplate: "Code derived from the document \"Report on the Programming Language\nHaskell 2010\", is distributed under the following license:\nCopyright (c) 2010 Simon Marlow\nThe authors intend this Report to belong to the entire Haskell community, and so we grant permission to copy and distribute it for any purpose, provided that it is reproduced in its entirety, including this Notice. Modified versions of this Report may also be copied and distributed for any purpose, provided that the modified version is clearly presented as such, and that it does not claim to be a definition of the Haskell 2010 Language.",
		Text:             "Code derived from the document \"Report on the Programming Language\nHaskell 2010\", is distributed under the following license:\nCopyright (c) 2010 Simon Marlow\nThe authors intend this Report to belong to the entire Haskell community, and so we grant permission to copy and distribute it for any purpose, provided that it is reproduced in its entirety, including this Notice. Modified versions of this Report may also be copied and distributed for any purpose, provided that the modified version is clearly presented as such, and that it does not claim to be a definition of the Haskell 2010 Language.",
		URIs:             []string{"https://fedoraproject.org/wiki/Licensing/Haskell_Language_Report_License"},
	})
}
