// Code generated by github.com/joshdk/license/spdxgen. DO NOT EDIT.

package spdx

func init() {
	licenses = append(licenses, License{
		Deprecated:       false,
		Identifier:       "Zed",
		Name:             "Zed License",
		OSIApproved:      false,
		StandardHeader:   "",
		StandardTemplate: "(c) Jim Davies, January 1995\nYou may copy and distribute this file freely.  Any queries and complaints should be forwarded to Jim.Davies@comlab.ox.ac.uk.\nIf you make any changes to this file, please do not distribute the results under the name `zed-csp.sty'.",
		Text:             "(c) Jim Davies, January 1995\nYou may copy and distribute this file freely.  Any queries and complaints should be forwarded to Jim.Davies@comlab.ox.ac.uk.\nIf you make any changes to this file, please do not distribute the results under the name `zed-csp.sty'.",
		URIs:             []string{"https://fedoraproject.org/wiki/Licensing/Zed"},
	})
}
