// Code generated by github.com/joshdk/license/spdxgen. DO NOT EDIT.

package spdx

func init() {
	licenses = append(licenses, License{
		Deprecated:       true,
		Identifier:       "GPL-2.0-with-font-exception",
		Name:             "GNU General Public License v2.0 w/Font exception",
		OSIApproved:      true,
		StandardHeader:   "",
		StandardTemplate: "\ufeffinsert GPL v2 text here\n\nFont Exception\n\nAs a special exception, if you create a document which uses this font, and embed this font or unaltered portions of this font into the document, this font does not by itself cause the resulting document to be covered by the GNU General Public License. This exception does not however invalidate any other reasons why the document might be covered by the GNU General Public License. If you modify this font, you may extend this exception to your version of the font, but you are not obligated to do so. If you do not wish to do so, delete this exception statement from your version.",
		Text:             "\ufeffinsert GPL v2 text here\n\nFont Exception\n\nAs a special exception, if you create a document which uses this font, and embed this font or unaltered portions of this font into the document, this font does not by itself cause the resulting document to be covered by the GNU General Public License. This exception does not however invalidate any other reasons why the document might be covered by the GNU General Public License. If you modify this font, you may extend this exception to your version of the font, but you are not obligated to do so. If you do not wish to do so, delete this exception statement from your version.",
		URIs:             []string{"http://www.gnu.org/licenses/gpl-faq.html#FontException"},
	})
}
