// Code generated by github.com/joshdk/licensor/spdxgen. DO NOT EDIT.

package spdx

func init() {
	licenses = append(licenses, License{
		Deprecated:       false,
		Identifier:       "Fair",
		Name:             "Fair License",
		OSIApproved:      true,
		StandardHeader:   "",
		StandardTemplate: "<<beginOptional>> Fair License<<endOptional>>\n<Copyright Information>\nUsage of the works is permitted provided that this instrument is retained with the works, so that any entity that uses the works is notified of this instrument.\nDISCLAIMER: THE WORKS ARE WITHOUT WARRANTY.",
		Text:             "Fair License\n<Copyright Information>\nUsage of the works is permitted provided that this instrument is retained with the works, so that any entity that uses the works is notified of this instrument.\nDISCLAIMER: THE WORKS ARE WITHOUT WARRANTY.",
		URIs:             []string{"http://www.opensource.org/licenses/Fair", "http://fairlicense.org/"},
	})
}
