// Code generated by github.com/joshdk/licensor/spdxgen. DO NOT EDIT.

package spdx

func init() {
	licenses = append(licenses, License{
		Deprecated:       false,
		Identifier:       "IBM-pibs",
		Name:             "IBM PowerPC Initialization and Boot Software",
		OSIApproved:      false,
		StandardHeader:   "",
		StandardTemplate: "This source code has been made available to you by IBM on an AS-IS basis. \u00a0Anyone receiving this source is licensed under IBM copyrights to use it in any way he or she deems fit, including copying it, modifying it, compiling it, and redistributing it either with or without modifications. \u00a0No license under IBM patents or patent applications is to be implied by the copyright license.\n\nAny user of this software should understand that IBM cannot provide technical support for this software and will not be responsible for any consequences resulting from the use of this software.\n\nAny person who transfers this source code or any derivative work must include the IBM copyright notice, this paragraph, and the preceding two paragraphs in the transferred software.\n\nCOPYRIGHT \u00a0\u00a0I B M \u00a0\u00a0CORPORATION 2002\nLICENSED MATERIAL \u00a0- \u00a0PROGRAM PROPERTY OF I B M",
		Text:             "This source code has been made available to you by IBM on an AS-IS basis. \u00a0Anyone receiving this source is licensed under IBM copyrights to use it in any way he or she deems fit, including copying it, modifying it, compiling it, and redistributing it either with or without modifications. \u00a0No license under IBM patents or patent applications is to be implied by the copyright license.\n\nAny user of this software should understand that IBM cannot provide technical support for this software and will not be responsible for any consequences resulting from the use of this software.\n\nAny person who transfers this source code or any derivative work must include the IBM copyright notice, this paragraph, and the preceding two paragraphs in the transferred software.\n\nCOPYRIGHT \u00a0\u00a0I B M \u00a0\u00a0CORPORATION 2002\nLICENSED MATERIAL \u00a0- \u00a0PROGRAM PROPERTY OF I B M",
		URIs:             []string{"http://git.denx.de/?p=u-boot.git;a=blob;f=arch/powerpc/cpu/ppc4xx/miiphy.c;h=297155fdafa064b955e53e9832de93bfb0cfb85b;hb=9fab4bf4cc077c21e43941866f3f2c196f28670d"},
	})
}
